dist: bionic
language: java

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

before_install:
  # output env info
  - ls -la
  - ls -l /usr/lib/jvm && ls /usr/lib/jvm/*
  - echo -e "JAVA_HOME=$JAVA_HOME\nPATH=$PATH\nSHELL=$SHELL"

after_success:
  - mvn clean cobertura:cobertura coveralls:report


before_cache:
  # clear maven self install
  - rm -rf $HOME/.m2/repository/com/oldratlee

cache:
  directories:
    - $HOME/.m2
